# Generated by Django 4.0.5 on 2022-06-17 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('dunya', 'Dunya'), ('teknoloji', 'Teknoloji'), ('saglik', 'Saglik'), ('politika', 'Politika'), ('bilim', 'Bilim'), ('stil', 'Stil'), ('kultur', 'Kultur'), ('cevre', 'Cevre')], default='dunya', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('excerpt', models.CharField(max_length=250)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
